services:
  - type: web
    name: authentiq
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app app:create_app db upgrade && gunicorn "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
