"""Challenge answers and challenge stat columns

Revision ID: 165aef838541
Revises: 62bd146bc441
Create Date: 2026-04-13 16:26:13.581345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165aef838541'
down_revision = '62bd146bc441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', 'question_id', name='uq_challenge_answer_user_question')
    )
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenger_correct_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_correct_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('challenger_time_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_time_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('opponent_time_ms')
        batch_op.drop_column('challenger_time_ms')
        batch_op.drop_column('opponent_correct_count')
        batch_op.drop_column('challenger_correct_count')

    op.drop_table('challenge_answer')
    # ### end Alembic commands ###
